/*******************************************************************************
	Generated by: DLL to C version 3.74
	Date: 2020-5-12
	Description: The declaration of functions and variables for Win32Dll.dll.
	Website: http://www.dll-decompiler.com
	Technical Support: support@dll-decompiler.com
*******************************************************************************/

#if !defined(_WIN32DLL_SUPP_H_0000E000_INCLUDED_)
#define _WIN32DLL_SUPP_H_0000E000_INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000


#include <windows.h>

#pragma pack(push)
#pragma pack(1)

#include "Win32Dll_rdata.h"
#include "Win32Dll_data.h"

__declspec(align(16)) struct stWin32Dll
{
	UCHAR Header[0x1000];
	UCHAR Text[0x7000];
	stWin32Dll_rdata Rdata;
	stWin32Dll_data Data;
	UCHAR Rsrc[0x1000];
	UCHAR Reloc[0x1000];
};

#pragma pack(pop)

__declspec(align(16)) extern stWin32Dll Win32Dll;

/* Data for initialization. */
extern UCHAR Win32Dll_InitData[0xE02];

extern HMODULE g_hWin32Dll;

/*
	Description: Access any address in the DLL.
	Parameters:
		rvaAddr: The RVA address you want to access.
*/
void* __stdcall Win32Dll_RVA(DWORD rvaAddr);

#define Win32Dll_VA(vaAddr) Win32Dll_RVA((vaAddr) - 0x10000000)


#endif // !defined(_WIN32DLL_SUPP_H_0000E000_INCLUDED_)